
REPLACE INTO `content_node_field_instance` (`field_name`, `type_name`, `weight`, `label`, `widget_type`, `widget_settings`, `display_settings`, `description`, `widget_module`, `widget_active`) VALUES
('field_additional_doc_file', 'document', 22, 'Additional documentation file', 'filefield_widget', 'a:5:{s:15:"file_extensions";s:106:"pdf doc docx xls xlsx ppt pptx pps ppsx odt ods odp odb odg odf zip gzip tar.gz tar 7z png jpg gif txt war";s:9:"file_path";s:0:"";s:18:"progress_indicator";s:3:"bar";s:21:"max_filesize_per_file";s:0:"";s:21:"max_filesize_per_node";s:0:"";}', 'a:9:{s:6:"weight";s:2:"22";s:6:"parent";s:26:"group_document_information";i:4;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:5:"label";a:2:{s:6:"format";s:5:"above";s:7:"exclude";i:0;}s:6:"teaser";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:4:"full";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:2;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:3;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:5:"token";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}}', '', 'filefield', 1),
('field_case_documentation', 'case', 23, 'Documentation', 'filefield_widget', 'a:5:{s:15:"file_extensions";s:106:"pdf doc docx xls xlsx ppt pptx pps ppsx odt ods odp odb odg odf zip gzip tar.gz tar 7z png jpg gif txt war";s:9:"file_path";s:0:"";s:18:"progress_indicator";s:3:"bar";s:21:"max_filesize_per_file";s:0:"";s:21:"max_filesize_per_node";s:0:"";}', 'a:9:{s:5:"label";a:2:{s:6:"format";s:5:"above";s:7:"exclude";i:0;}s:6:"teaser";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:4:"full";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:4;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:2;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:3;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:11:"email_plain";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:10:"email_html";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:5:"token";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}}', '', 'filefield', 1),
('field_documentation', 'news', 9, 'Documentation', 'filefield_widget', 'a:5:{s:15:"file_extensions";s:106:"pdf doc docx xls xlsx ppt pptx pps ppsx odt ods odp odb odg odf zip gzip tar.gz tar 7z png jpg gif txt war";s:9:"file_path";s:0:"";s:18:"progress_indicator";s:3:"bar";s:21:"max_filesize_per_file";s:0:"";s:21:"max_filesize_per_node";s:0:"";}', 'a:8:{s:6:"weight";s:1:"9";s:6:"parent";s:21:"group_news_basic_info";i:4;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:5:"label";a:2:{s:6:"format";s:5:"above";s:7:"exclude";i:0;}s:6:"teaser";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:4:"full";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:2;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:3;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}}', '', 'filefield', 1),
('field_profile_cv', 'profile', 10, 'Curriculum Vitae', 'filefield_widget', 'a:5:{s:15:"file_extensions";s:57:"jpg jpeg gif png txt doc docx pdf ppt pps odt ods odp zip";s:9:"file_path";s:0:"";s:18:"progress_indicator";s:3:"bar";s:21:"max_filesize_per_file";s:0:"";s:21:"max_filesize_per_node";s:0:"";}', 'a:9:{s:5:"label";a:2:{s:6:"format";s:5:"above";s:7:"exclude";i:0;}s:6:"teaser";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:4:"full";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:4;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:2;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:3;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:11:"email_plain";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:10:"email_html";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:5:"token";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}}', '', 'filefield', 1),
('field_project_issues_attachement', 'project_issue', 8, 'Attachment', 'filefield_widget', 'a:5:{s:15:"file_extensions";s:106:"pdf doc docx xls xlsx ppt pptx pps ppsx odt ods odp odb odg odf zip tar.gz tar gzip 7z png jpg gif txt war";s:9:"file_path";s:0:"";s:18:"progress_indicator";s:3:"bar";s:21:"max_filesize_per_file";s:0:"";s:21:"max_filesize_per_node";s:0:"";}', 'a:9:{s:5:"label";a:2:{s:6:"format";s:5:"above";s:7:"exclude";i:0;}s:6:"teaser";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:4:"full";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:4;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:2;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:3;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:11:"email_plain";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:10:"email_html";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:5:"token";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}}', '', 'filefield', 1),
('field_release_document', 'project_release', 16, 'Documents', 'filefield_widget', 'a:5:{s:15:"file_extensions";s:106:"pdf doc docx xls xlsx ppt pptx pps ppsx odt ods odp odb odg odf zip tar.gz tar gzip 7z png jpg gif txt war";s:9:"file_path";s:0:"";s:18:"progress_indicator";s:3:"bar";s:21:"max_filesize_per_file";s:0:"";s:21:"max_filesize_per_node";s:0:"";}', 'a:9:{s:6:"weight";s:2:"16";s:6:"parent";s:26:"group_release_attachements";s:5:"label";a:1:{s:6:"format";s:5:"above";}s:6:"teaser";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:4:"full";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:4;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:2;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}i:3;a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}s:5:"token";a:2:{s:6:"format";s:7:"default";s:7:"exclude";i:0;}}', 'For the maturity process, you can attach asset assessment reports to this release', 'filefield', 1);


REPLACE INTO `variable` (`name`, `value`) VALUES
('upload_extensions_default', 's:65:"jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp zip docx tar";'),
('upload_extensions_14', 's:65:"jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp zip docx tar";'),
('upload_extensions_16', 's:65:"jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp zip docx tar";'),
('upload_extensions_2', 's:65:"jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp zip docx tar";'),
('upload_extensions_3', 's:65:"jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp zip docx tar";'),
('upload_extensions_5', 's:65:"jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp zip docx tar";'),
('upload_extensions_6', 's:65:"jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp zip docx tar";'),
('upload_extensions_9', 's:65:"jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp zip docx tar";'),
('project_release_file_extensions', 's:70:"zip gz tar bz2 rar tgz tar dmg rpm deb exe xsd xml xmi txt rdf ear jar";');
