
UPDATE `variable` SET `value` = 's:6:"Joinup";' WHERE `name` = 'site_name';
UPDATE `variable` SET `value` = 'a:31:{i:1;s:20:"event_comment_update";i:2;s:20:"event_comment_delete";i:3;s:18:"event_comment_view";i:5;s:23:"event_comment_unpublish";i:8;s:18:"event_node_presave";i:9;s:15:"event_node_view";i:10;s:17:"event_node_delete";i:11;s:10:"event_init";i:12;s:10:"event_cron";i:13;s:26:"event_taxonomy_term_insert";i:14;s:26:"event_taxonomy_term_update";i:15;s:17:"event_user_insert";i:16;s:17:"event_user_update";i:17;s:15:"event_user_view";i:18;s:17:"event_user_delete";i:20;s:17:"event_user_logout";i:21;s:28:"event_flag_flagged_bookmarks";i:22;s:30:"event_flag_unflagged_bookmarks";i:23;s:32:"event_flag_flagged_editor_choice";i:24;s:34:"event_flag_unflagged_editor_choice";i:27;s:37:"event_flag_flagged_i_use_this_project";i:28;s:39:"event_flag_unflagged_i_use_this_project";i:29;s:28:"event_heartbeat_comment_post";i:30;s:37:"event_heartbeat_related_comment_post_";i:31;s:16:"event_shout_post";i:33;s:22:"event_og_user_approved";i:35;s:37:"event_userpoints_event_points_awarded";i:37;s:28:"event_workflow_comment_added";i:41;s:24:"event_og_become_co_admin";i:42;s:55:"rules_heartbeat_when_user_edit_a_page_log_user_activity";i:43;s:11:"rules_set_1";}' WHERE `name` = 'rules_inactive_sets';
UPDATE `variable` SET `value` = 's:384:"<p>Dear [recipient-firstname],</p>\r\n<div>\r\n<p>User [field_firstname-formatted] [field_lastname-formatted] has created a new document &quot;[title]&quot; in [isa_group_type] [ogname].</p>\r\n<p>To reach this document, click on following link : [isa_node_link]</p>\r\n<p><span class="Apple-style-span"><span class="Apple-style-span">[site-name] </span></span>Team</p>\r\n</div>\r\n<p>&nbsp;</p>";' WHERE `name` = 'community_create_document_to_facilitators_mail_body';
UPDATE `variable` SET `value` = 's:386:"<p>Dear [recipient-firstname],</p>\r\n<div>\r\n<p>User [field_firstname-formatted] [field_lastname-formatted] has created a new wiki page &quot;[title]&quot; in [isa_group_type] [ogname].</p>\r\n<p>To reach this wiki page, click on following link : [isa_node_link]</p>\r\n<p><span class="Apple-style-span"><span class="Apple-style-span">[site-name]</span></span> Team</p>\r\n</div>\r\n<p>&nbsp;</p>";' WHERE `name` = 'community_create_wiki_to_facilitators_mail_body';
UPDATE `variable` SET `value` = 's:1:"0";' WHERE `name` = 'captcha_persistence';
UPDATE `variable` SET `value` = 's:6:"Joinup";' WHERE `name` = 'site_slogan';
UPDATE `variable` SET `value` = 's:464:"Dear !username,\r\n\r\nThank you for registering !site  platform. You may now log in to !login_uri using the following username and password:\r\n\r\nUsername: !username\r\nPassword: !password\r\n\r\nYou must confirm you registration by clicking on this link or copying and pasting it in your browser:\r\n\r\n!login_url\r\n\r\nThis is a one-time login, so it can be used only once.\r\n\r\nAfter logging in, you will be redirected to !edit_uri so you can change your password.\r\n\r\n\r\n!site Team";' WHERE `name` = 'user_mail_register_no_approval_required_body';
UPDATE `variable` SET `value` = 's:136:"Dear [recipient-firstname],\r\n\r\nYour account has been reactivated. You are now able to connect again to the !site platform.\r\n\r\n!site Team";' WHERE `name` = 'user_mail_status_activated_body';
UPDATE `variable` SET `value` = 's:173:"Dear [recipient-firstname],\r\n\r\nYour account has been blocked. In case of error, you can contact us thanks to the address dlfr-ce-drupal-isa.ext@atosorigin.com.\r\n\r\n!site Team";' WHERE `name` = 'user_mail_status_blocked_body';
UPDATE `variable` SET `value` = 'i:1;' WHERE `name` = 'contexthelp_help_button_in_theme';
UPDATE `variable` SET `value` = 's:1:"0";' WHERE `name` = 'language_content_type_profile';
UPDATE `variable` SET `value` = 's:46:"<p>You should connect to display this page</p>";' WHERE `name` = 'anonymous_connect';
UPDATE `variable` SET `value` = 's:61:"jpg jpeg gif png txt doc xls pdf ppt pps odt ods odp zip docx";' WHERE `name` = 'upload_extensions_default';
UPDATE `variable` SET `value` = 's:384:"<p>Dear [recipient-firstname],</p>\r\n<div>\r\n<p>User [field_firstname-formatted] [field_lastname-formatted] has created a new forum topic &quot;[title]&quot; in [isa_group_type] [ogname].</p>\r\n<p>To reach this topic, click on following link : [isa_node_link]</p>\r\n<p><span class="Apple-style-span"><span class="Apple-style-span">[site-name] </span></span>Team</p>\r\n</div>\r\n<p>&nbsp;</p>";' WHERE `name` = 'community_create_topic_to_facilitators_mail_body';
UPDATE `variable` SET `value` = 's:340:"<p>Dear [recipient-firstname],</p>\r\n<p>User [field_firstname-formatted] [field_lastname-formatted] has created news &quot;[title]&quot; in [isa_group_type] [ogname].</p>\r\n<p>To reach this news, click on following link : [isa_node_link]</p>\r\n<p><span class="Apple-style-span"><span class="Apple-style-span">[site-name]</span></span> Team</p>";' WHERE `name` = 'community_create_news_to_facilitators_mail_body';
UPDATE `variable` SET `value` = 's:8:"Joinup: ";' WHERE `name` = 'prefix_subject_mail_title';
UPDATE `variable` SET `value` = 's:35:"Join the new collaboration platform";' WHERE `name` = 'invite_joinup_mail_title';
UPDATE `variable` SET `value` = 's:803:"<p>Dear future user,</p>\r\n<p>[author_firstname] [author_lastname]&nbsp; <span class="Apple-style-span"><span class="Apple-style-span">(</span></span>[profile_company]<span class="Apple-style-span"><span class="Apple-style-span">) wants to invite you to join [site-name].</span></span></p>\r\n<p>[invite_message]</p>\r\n<p><span class="Apple-style-span"><span class="Apple-style-span"> Follow this link to register on </span></span><span class="Apple-style-span"><span class="Apple-style-span">[site-name] :&nbsp; [invite_link] </span></span></p>\r\n<p>For a complete list of advantages of membership, click here [about_us_link].</p>\r\n<p>You want to report a spam? You can send us an email to [site-mail].</p>\r\n<p><span class="Apple-style-span"><span class="Apple-style-span">[site-name] Team</span></span></p>";' WHERE `name` = 'invite_joinup_mail_body';
UPDATE `variable` SET `value` = 's:12:"Join [title]";' WHERE `name` = 'invite_group_mail_title';
UPDATE `variable` SET `value` = 's:885:"<p>Dear [recipient-firstname],</p>\r\n<p>[author_firstname] [author_lastname] has invited you to join the [isa_group_type] <em>[title]</em> on [site-name].</p>\r\n<p>[invite_message]</p>\r\n<p>About the [isa_group_type] <em>[title]</em>: [group_abstract].</p>\r\n<p>To join this [isa_group_type] click on the following link [isa_node_link]</p>\r\n<p>As a member, you will be able to participate actively in the activities of this [isa_group_type]. You will be able to create and highlight content, such as blogs, news items, events, useful software or semantic asset and participate in the discussion forums and wikis of the community. You will be automatically notified of any activities and new content.</p>\r\n<p>For a complete list of advantages of membership, click here [about_us_link].</p>\r\n<p>You want to report a spam? You can send us an email to [site-mail].</p>\r\n<p>[site-name] Team</p>";' WHERE `name` = 'invite_group_mail_body';
UPDATE `variable` SET `value` = 'a:6:{i:2;s:18:"authenticated user";i:6;s:13:"administrator";i:14;s:24:"clearing process manager";i:16;s:6:"expert";i:5;s:6:"member";i:3;s:9:"moderator";}' WHERE `name` = 'roles';
UPDATE `variable` SET `value` =  's:37:"form-e541c58bc4eb0eeb37ee13d0ed84234f";' WHERE `name` = 'form_build_id_profile'
